language: python
python:
- '3.6'
script:
- python setup.py test
- python setup.py sdist
deploy:
  provider: pypi
  user: lfoppiano
  password:
    secure: AL3z9vnQ//JMjJIwk4iaGSdhs7wbdgBL5Hp/umCll68jQ0vmaHypV7A4KQYiriSxgeGfG6s9LQRvyUDUmYmVgztrPJtoo235esNC13UGts3TTC4qapjhYxM7zFMfOXzD1mHaxq1SI0uR3MA5+lrxVitc46ubrZo1/qqknGVzwnE6YYXL7UwTDedLTDbwCnALDrc9ACciqI0xYPc59QOrcDeN1AcRRZx/oeDHrekgalvwNGJHYNfyKBWsTdeAkguIEGV1xYIv9dUYOFWHRyi+L09M7hBDFkzG854V7jYorr2CuuuBEZPYMFmpw3rx7+h86ynwJmycn6CmszgFvY3tf4MGTJmFCGY5HJo3TberBrKtE7C65n2vCS8JMu0I/FlKegFYqgMOs17EH5t9AybozsOjhfH8B4p5I21AMQqcgi/qB5xPwLq1UxVWJK3E3diAa0a1srKoBBdp2iG4LQywxs5dx8sUhas5p+HoDBEfPKBvV+dyBiLTVrVt7GZwG7wbZt2ENhwHyT33JiSk6f2MprY7HGplYu/RPQp23adpTEl7Gfwz3j/CDfWpUbv9sZF5g3W+ncJpA3WBHF1M+cTD19fOS4Y2yvZvXtQ8dqhx4s2Ydx1HnId3XqA3YHNb1DuTYNLZqNmI4K4rz6tQGwAh2rtjCo5pzlD7g3UaOwIKfkI=
  on:
    tags: true
