language: python
python:
- '3.6'
script:
  - python setup.py test
  - python setup.py sdist
  
deploy:
  provider: pypi
  user: lfoppiano
  password:
    secure: qNGXHnaECA5e4zGpQS3LNSyDouaf5Zp7mbaLOG/TkU8yMAvAt9foKfbMpFc0abrRFQmoERC5blSK0iu3N1XUxW2h3sQoepMr1pdbctAAjgitLLBOiP7DNn1qlcl7mAC/LpkPEEGsK5ffOKqg9TPF6MAIQSySylV9hD8EoBfV466ugYFtSP47GWJDfwj+EhxKCH/aWDDE2iaGKjqUeZUF/qALIEiMA9LqNRJOE2XvLlQYcoXS5/qE5EhlfKMfA/Z5HFjG9gducQ4Al+1eZsVrbc6aJP1VlCr9zkEeRoIxkn/qfCjkfHR41NfMP2lqx86fMwsawPnorLjaGoPtoNGbQa7Qbzf01ckuUE8hDbOaCGJyxCf9z3MBrfjP9bv9BwCU3FKUQIbY8+fD9lh3Gl1GkYQQDJQB1kdb9ohqA/5VriaPBJMpUj3a9zQzY28UTkrJzgxMCAbM8Q8ZXqOTtE7BRyBHRkBukHpbD7P6ifyIAZRbvDeK10WLvxDgcZ+1Z5pR3EHBVQaAPHoa9+uiBrXTe+/A8n12mfAdw1eGArpDM9GZzX/RJlne20IWSlXXNsbcUSKFwcmFIIbyXJWR0LsJos+0ncma0PbqUZ0Tb5d1yZVEC3LymixZ0GA+exlkSKGuHxy6OKV4KIKfew+eAq4ThXb6S7sprss99piLIzH7ycY=
  on:
    tags: true